
language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta

script:
- cargo build --release --bin evolvim
- cargo test --verbose --all
