[package]
authors = ["Sybrand Aarnoutse (syberant)"]
name = "evolvim"
version = "0.1.0"

[dependencies]
nalgebra = "0.16.0"
noise = "0.5.1"
piston_window = "0.80.0"
rand = "0.5.4"

[dependencies.piston2d-graphics]
version = "0.26.0"
features = ["glyph_cache_rusttype"]

[features]
bench = []

[lib]
name = "lib_evolvim"
path = "./src/lib/mod.rs"
